spring:
  cache:
    type: redis
  redis:
    host: localhost
    port: 6379
    timeOfLife: 60000
  data:
    mongodb:
      database: coderhouse
      host: localhost
      port: 27017
jwt:
  expiration: 60000
  secret: springbootjwtcoderhouse
server:
  port: 8080